### ISSUE TITLE
Offloading google's CDN onto **MY** server. 

### ISSUE THREAD

**Issue by snaildos** [snaildos/SnailDOS-Desktop#23]
we use google, google is naughty boi cia man, so we move from gogle to our own cdn. 
ETA: 2 days or more.

**Comment by snaildos** [comment]
Late.

**Comment by snaildos** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [To Do](https://trello.com/c/CdIjUi22/3-to-do)

**Comment by Ll3ma** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CDN Rewrite](https://trello.com/c/scRcTsxO/21-cdn-rewrite)

**Comment by snaildos** [comment]
Project semi archived. Waiting for api v2 release.
